version: '3.1'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  backend:
    container_name: backend
    restart: always
    build:
      context: .
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
    networks:
      - app-network

volumes:
  mongodb-data:
networks:
  app-network:
